version: '3'
services:
  setup-cluster:
    image: elasticsearch:${STACK_VERSION}
    container_name: setup-cluster
    volumes:
      - ./setup-cluster.sh:/setup-cluster.sh
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    user: "0"
    command: >
      bash /setup-cluster.sh

  es-cluster-01:
    depends_on: 
      - setup-cluster
    image: elasticsearch:${STACK_VERSION}
    container_name: es-cluster-01
    volumes:
      - ./data/esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es-cluster-01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es-cluster-01,es-cluster-02,es-cluster-03,es-cluster-04
      - discovery.seed_hosts=es-cluster-02,es-cluster-03,es-cluster-04
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      # - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -u elastic:${ELASTIC_PASSWORD} -s -f localhost:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
<<<<<<< HEAD
      retries: 120
=======
      retries: 20
>>>>>>> 3340de70352ec31059ec94c7ae3e6ce9d202d5e5

  es-cluster-02:
    image: elasticsearch:${STACK_VERSION}
    container_name: es-cluster-02
    depends_on:
      - es-cluster-01
    volumes:
      # - ./certs:/usr/share/elasticsearch/config/certs
      - ./data/esdata02:/usr/share/elasticsearch/data
    ports:
      - '9202:9200'
      - '9302:9300'
    environment:
      - node.name=es-cluster-02
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es-cluster-01,es-cluster-02,es-cluster-03,es-cluster-04
      - discovery.seed_hosts=es-cluster-01,es-cluster-03,es-cluster-04
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      # - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -u elastic:${ELASTIC_PASSWORD} -s -f localhost:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
<<<<<<< HEAD
      retries: 120
=======
      retries: 20
>>>>>>> 3340de70352ec31059ec94c7ae3e6ce9d202d5e5


  es-cluster-03:
    image: elasticsearch:${STACK_VERSION}
    container_name: es-cluster-03
    depends_on:
      - es-cluster-01
    volumes:  
      - ./data/esdata03:/usr/share/elasticsearch/data
    ports:
      - '9203:9200'
      - '9303:9300'
    environment:
      - node.name=es-cluster-03
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es-cluster-01,es-cluster-02,es-cluster-03,es-cluster-04
      - discovery.seed_hosts=es-cluster-01,es-cluster-02,es-cluster-04
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      # - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -u elastic:${ELASTIC_PASSWORD} -s -f localhost:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 120


  es-cluster-04:
    image: elasticsearch:${STACK_VERSION}
    container_name: es-cluster-04
    depends_on:
      - es-cluster-01
    volumes:  
      - ./data/esdata04:/usr/share/elasticsearch/data
    ports:
      - '9204:9200'
      - '9304:9300'
    environment:
      - node.name=es-cluster-04
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es-cluster-01,es-cluster-02,es-cluster-03,es-cluster-04
      - discovery.seed_hosts=es-cluster-01,es-cluster-02,es-cluster-03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      # - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -u elastic:${ELASTIC_PASSWORD} -s -f localhost:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
<<<<<<< HEAD
      retries: 120
=======
      retries: 20
>>>>>>> 3340de70352ec31059ec94c7ae3e6ce9d202d5e5


        
  kibana-cluster:
    depends_on:
      es-cluster-01:
        condition: service_healthy
      es-cluster-02:
        condition: service_healthy
      es-cluster-03:
        condition: service_healthy
      es-cluster-04:
        condition: service_healthy
    image: kibana:${STACK_VERSION}
    container_name: kibana-cluster
    ports:
        - ${KIBANA_PORT}:5601
    volumes:
      - ./data/kibanadata:/usr/share/kibana/data

    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es-cluster-01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

